### ISSUE TITLE
Звездный рейтинг для MODX Evolution

### ISSUE THREAD

**Issue by muhammadi** [vanchelo/MODX-Evolution-Star-Rating#2]
Здравствуйте.
Установил рэйтинг, но почему-то звёзды на странице не выводятся.
http://bicycleservice.org/veloservice-magicsport.html
Не могу разобраться почему.
Вывожу так:

```
[!star_rating? &id=`[*id*]`!]
```

и так:

```
[!star_rating? &id=`[*id*]` &imagesPath=`assets/snippets/star_rating/assets/img/alt`  &tpl=`@CHUNK:star_rating`!]
```

результата нет. В чём может быть причина?
Помогите пожалуйста!

**Comment by vanchelo** [comment]
А у вас чанк `star_rating` присутствует?

**Comment by muhammadi** [comment]
Да, конечно присутствует.
Настраивал как в описании.
Ничего не выводит :(

------20 марта 2015 г.  Вы писали:------------------ 

А у вас чанк star_rating присутствует?
—
Reply to this email directly or view it on GitHub.

---

С  уважением,
Konstantin
OROBANK приглашает партнёров: http://hr-orobank.ru

**Comment by vanchelo** [comment]
Смотрите консоль, у вас ошибки в JS коде поэтому не исполняется скрипт рейтинга

**Comment by muhammadi** [comment]
Посмотрите пожалуйста если нужно, изнутри:
Логин: test
Пароль: 555555



------20 марта 2015 г.  Вы писали:------------------ 

А у вас чанк star_rating присутствует?
—
Reply to this email directly or view it on GitHub.




----------------------
С  уважением,
Konstantin
OROBANK приглашает партнёров: http://hr-orobank.ru

**Comment by vanchelo** [comment]
Я обновил версию https://github.com/vanchelo/MODX-Evolution-Star-Rating/releases/tag/v1.0.4-raty
Попробуйте её поставить

**Comment by muhammadi** [comment]
Поставил новую. Настроил заново. Не выводится рейтинг. Из чанка наверное ничего не поддтягивается.

**Comment by vanchelo** [comment]
Попробуйте удалить таблицы рейтинга из базы данных и потом установить заново

**Comment by muhammadi** [comment]
Проделал это. Установил по новой. Всёравно - не выводит.

**Comment by vanchelo** [comment]
ошибки в отчете пишет какие-нибудь?

**Comment by muhammadi** [comment]
[Sat Mar 21 04:42:22 2015] [error] [client 178.121.212.51] File does not exist: /home/yourany2/public_html/bicycleservice.org/assets/snippets/star_rating/module/libs/ngtoast, referer: http://bicycleservice.org/manager/index.php?a=112&id=3
[Sat Mar 21 04:39:35 2015] [error] [client 178.121.212.51] File does not exist: /home/yourany2/public_html/bicycleservice.org/assets/snippets/star_rating/module/libs/ngtoast, referer: http://bicycleservice.org/manager/index.php?a=112&id=3
[Sat Mar 21 04:37:09 2015] [error] [client 178.121.212.51] File does not exist: /home/yourany2/public_html/bicycleservice.org/assets/snippets/star_rating/module/libs/ngtoast, referer: http://bicycleservice.org/manager/index.php?a=112&id=3
[Sat Mar 21 04:23:31 2015] [error] [client 178.121.212.51] File does not exist: /home/yourany2/public_html/bicycleservice.org/assets/templates/site/images/tipsy.gif, referer: http://bicycleservice.org/assets/templates/site/css/shortcodes.css
[Sat Mar 21 04:23:09 2015] [error] [client 178.121.212.51] File does not exist: /home/yourany2/public_html/bicycleservice.org/assets/snippets/star_rating/module/libs/ngtoast
[Sat Mar 21 04:12:58 2015] [error] [client 213.110.130.138] File does not exist: /home/yourany2/public_html/bicycleservice.org/assets/snippets/star_rating/assets/js, referer: http://bicycleservice.org/veloservice-magicsport.html

**Comment by vanchelo** [comment]
Это не то, я имел ввиду журнал ошибок в MODX

**Comment by vanchelo** [comment]
Отчет -> Просмотр событий

**Comment by muhammadi** [comment]
Там ругается на Snippet - anythingRating. Я его удалил. Из базы данных тоже.
Всё-равно, пока без изменений.

**Comment by vanchelo** [comment]
Дайте мне административный доступ

**Comment by muhammadi** [comment]
Поставил административный доступ. Вышел.

**Comment by vanchelo** [comment]
ок

**Comment by vanchelo** [comment]
Я не могу у вас в админке файлы редактировать, они не сохраняются

**Comment by muhammadi** [comment]
для этого нужно права выставить на сервере? подскажите, я сделаю

**Comment by vanchelo** [comment]
а фтп есть?

**Comment by muhammadi** [comment]
да, сейчас дам...

**Comment by vanchelo** [comment]
на почту отправьте brezhnev.ivan@yahoo.com

**Comment by muhammadi** [comment]
Отправил на brezhnev.ivan@yahoo.com

**Comment by vanchelo** [comment]
всё http://bicycleservice.org/veloservice-magicsport.html

**Comment by muhammadi** [comment]
Круть!!!! Волшебник, как вы это сделали? В чем была проблема?

**Comment by vanchelo** [comment]
ошибка была у меня в коде) я её исправил, а в админке не получалось, изменения файлов не сохранялись

**Comment by muhammadi** [comment]
Большое прибольшое спасибо вам за помощь и за полезную программу!

**Comment by vanchelo** [comment]
Пожалуйста)

**Comment by vanchelo** [comment]
дальше сами разберетесь?

**Comment by muhammadi** [comment]
Да, попробую разобраться сам, спасибо!

**Comment by Al4ek** [comment]
Я дико извиняюсь у меня та же проблема на локалке. Выводится сам сниппет но не выводится модуль. (Дизайн есть, функций нет из-за двух ошибок)

Не нажимается кнопка Обновить и не выводится кол-во. Такие ошибки

http://localhost/assets/snippets/star_rating/module/processors/connector.php Failed to load resource: the server responded with a status of 404 (Not Found) 

тут путь идёт почему-то без i (папка с сайтом) То есть файл такой есть, по пути с i http://localhost/i/ но путь не правильный, нет /i/ (то есть base href)

Также, нет http://localhost/i/assets/snippets/star_rating/module/libs/ngtoast/ngToast.min.css -файла
как и нет вообще папки ngtoast

Буду рад если найдётся минутка помочь, если это не заставит труда! Спасибо!
