### ISSUE TITLE
Не работает модуль "star_rating" на Evolution 2.0, MySql 5.7, PHP 7.2. General error: 2014 by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

### ISSUE THREAD

**Issue by M0LFAR** [vanchelo/MODX-Evolution-Star-Rating#9]
При попытке установки получил ошибку:
![image](https://user-images.githubusercontent.com/28487781/57680104-8a786100-7635-11e9-8966-e28d1011c7f4.png)
Решил установить вручную: добавил таблицы с setup.sql, в результате сам модуль просто сжирает память, на этапе коннекта, при этом записи с фронта добавляются в базу.
![image](https://user-images.githubusercontent.com/28487781/57680036-6026a380-7635-11e9-8a0e-5989681e06b9.png)
Могу дать доступ для теста. Заранее благодарю за помощь.

**Comment by ghost** [comment]
Добрый день, закомментируйте строку https://github.com/vanchelo/MODX-Evolution-Star-Rating/blob/1ed5497d26c267a003e1d45c8566ba81ec34e748/assets/snippets/star_rating/starrating.class.php#L535

**Comment by vanchelo** [comment]
@HubraBibik Думаете стоит выпилить?

**Comment by ghost** [comment]
По крайней мере так устанавливается на новых версиях php и modx, наверное устаревшая конструкция SQL. Единственное, что не работает это отображение оценок в модуле, еще не смотрел ошибки.

**Comment by vanchelo** [comment]
Не похоже чтобы `START TRANSACTION` считалась устаревшей https://dev.mysql.com/doc/refman/8.0/en/commit.html
